-- Crear tabla de órdenes (sin RLS)
create table ordenes (
    id bigint generated by default as identity primary key,
    numero text not null,
    fecha timestamptz not null default now(),
    productos jsonb not null,
    envio jsonb not null,
    pago jsonb not null,
    subtotal numeric not null,
    total numeric not null,
    created_at timestamptz not null default now()
);

-- Desactivar Row Level Security para desarrollo
alter table ordenes disable row level security;
