-- Crear tabla de categorías (sin RLS)
create table categorias (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    nombre text not null,
    imagen text not null default 'img/placeholder.jpg',
    descripcion text not null default '',
    created_at timestamptz not null default now()
);

-- Desactivar Row Level Security para desarrollo
alter table categorias disable row level security;

-- Insertar categorías iniciales
insert into categorias (slug, nombre, imagen, descripcion) values
    ('procesadores', 'Procesadores', 'img/categoria-procesadores.jpg', 'CPUs de última generación Intel y AMD para todas las necesidades'),
    ('memorias', 'Memorias RAM', 'img/categoria-ram.jpg', 'Módulos de memoria DDR4 y DDR5 de alta velocidad'),
    ('discos', 'Discos SSD', 'img/categoria-ssd.jpg', 'Unidades de estado sólido NVMe y SATA para máximo rendimiento'),
    ('placas-video', 'Placas de Video', 'img/categoria-placas-video.jpg', 'GPUs NVIDIA y AMD para gaming y trabajo profesional'),
    ('motherboards', 'Motherboards', 'img/categoria-motherboards.jpg', 'Placas madre con los últimos chipsets y conectividad'),
    ('monitores', 'Monitores', 'img/categoria-monitores.jpg', 'Pantallas Full HD, 4K y ultra-wide para gaming y trabajo'),
    ('coolers', 'Coolers', 'img/categoria-coolers.jpg', 'Sistemas de refrigeración por aire y líquida para tu equipo'),
    ('fuentes', 'Fuentes', 'img/categoria-fuentes.jpg', 'Fuentes de alimentación certificadas de alta eficiencia'),
    ('gabinetes', 'Gabinetes', 'img/categoria-gabinetes.jpg', 'Torres con excelente flujo de aire y diseño');
